# Generated by Django 3.2 on 2023-12-25 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231225_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'Код верификации имейла', 'verbose_name_plural': 'Код верификации имейла'},
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.UUIDField(unique=True, verbose_name='Код подтверждения email'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания кода верификации'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expiration',
            field=models.DateTimeField(verbose_name='Время истечения срока действия кода верификации'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
