# Generated by Django 3.2 on 2023-12-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20231225_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified_email',
            field=models.BooleanField(default=False, verbose_name='Подтвердил ли пользователь свой email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='users_images',
            field=models.ImageField(blank=True, null=True, upload_to='users_image/', verbose_name='Изображение пользователя'),
        ),
    ]
